drop table if exists product CASCADE;
create table product
(
    id       bigint generated by default as identity,
    name     varchar(255),
    quantity integer,
    primary key (id)
);

drop table if exists errorcode_data CASCADE;
create table errorcode_data
(
    id     bigint generated by default as identity,
    code   varchar(255),
    locale varchar(255),
    name   varchar(255),
    reason varchar(255),
    primary key (id)
);
